// // let mydate=new Date()
// // // console.log(mydate.toString())
// // // console.log(mydate.toLocaleString())
// // // console.log(mydate.toJSON())
// // // console.log(mydate.toLocaleDateString())
// // //  console.log(typeof mydate)
//   let mycreated=new Date("2023-01-14")
// // // console.log(mycreated.toString())
// // // console.log(mycreated.toLocaleString())
// // // console.log(mycreated.toString())
// // console.log(mycreated.toLocaleString())
// let mytime=Date.now()
// // console.log(mytime)
// // console.log(mycreated.getTime())
// console.log(Math.floor(mytime/1000))
let datea=new Date()
console.log(datea)
console.log(datea.getMonth())
console.log(datea.getDay())
console.log(datea.getFullYear())
datea.toLocaleString('dafault',{
    weekday:"long"
    
})